### ISSUE TITLE
好家伙空的

### ISSUE THREAD

**Issue by APLaS-Plus** [Mzying2001/DS-SZTU#1]

**Comment by APLaS-Plus** [comment]
nothing

**Comment by Mzying2001** [comment]
![efc2b5f2804b63cbaf377d5cacd5eff6](https://github.com/Mzying2001/DS-SZTU/assets/41951400/c2190501-6067-4b74-b0f1-fa3f8c16613e)

**Comment by APLaS-Plus** [comment]
抱歉学长，我的GitHub发病，今天显示不出东西了T^T
